"""Turn Barcelona's district GeoJSON into compact SVG paths for the barrio map.

Source: https://github.com/martgnz/bcn-geodata (Ajuntament de Barcelona open data).
Usage: python3 scripts/build-districts.py districtes.geojson > src/data/bcnDistricts.ts
"""
import json, math, sys

W = 1000  # viewBox width; height follows the city's aspect ratio
TOL = 1.2  # Douglas-Peucker tolerance in viewBox units
MIN_AREA = 40  # drop slivers (port piers etc.) smaller than this, in viewBox units²

feats = json.load(open(sys.argv[1]))['features']

def rings(g):
    return [p[0] for p in (g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']])]

pts = [pt for f in feats for r in rings(f['geometry']) for pt in r]
lat0 = sum(p[1] for p in pts) / len(pts)
k = math.cos(math.radians(lat0))
xs = [p[0] * k for p in pts]; ys = [-p[1] for p in pts]
minx, maxx, miny, maxy = min(xs), max(xs), min(ys), max(ys)
s = W / (maxx - minx)
H = round((maxy - miny) * s)
proj = lambda p: ((p[0] * k - minx) * s, (-p[1] - miny) * s)

def dp(points, tol):
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    i, dmax = 0, 0
    for j in range(1, len(points) - 1):
        d = abs(dy * points[j][0] - dx * points[j][1] + x2 * y1 - y2 * x1) / norm
        if d > dmax:
            i, dmax = j, d
    if dmax <= tol:
        return [points[0], points[-1]]
    return dp(points[: i + 1], tol)[:-1] + dp(points[i:], tol)

def area_centroid(r):
    a = cx = cy = 0
    for (x0, y0), (x1, y1) in zip(r, r[1:] + r[:1]):
        c = x0 * y1 - x1 * y0
        a += c; cx += (x0 + x1) * c; cy += (y0 + y1) * c
    a /= 2
    return abs(a), (cx / (6 * a), cy / (6 * a)) if a else r[0]

out = []
for f in sorted(feats, key=lambda f: f['properties']['DISTRICTE']):
    parts = []
    for r in rings(f['geometry']):
        pr = [proj(p) for p in r]
        a, c = area_centroid(pr)
        if a < MIN_AREA:
            continue
        # Closed rings start and end on the same point, so simplify each half separately.
        m = len(pr) // 2
        simp = dp(pr[: m + 1], TOL)[:-1] + dp(pr[m:], TOL)
        parts.append((a, c, 'M' + 'L'.join(f'{x:.0f},{y:.0f}' for x, y in simp) + 'Z'))
    parts.sort(key=lambda p: -p[0])
    cx, cy = parts[0][1]
    out.append({
        'id': f['properties']['DISTRICTE'],
        'name': f['properties']['NOM'],
        'cx': round(cx), 'cy': round(cy),
        'd': ''.join(p[2] for p in parts),
    })

print('// Generated by scripts/build-districts.py — do not edit by hand.')
print('// Source: Ajuntament de Barcelona open data via github.com/martgnz/bcn-geodata')
print(f'export const BCN_VIEWBOX = {{ width: {W}, height: {H} }}')
print('export const BCN_DISTRICT_SHAPES = ' + json.dumps(out, ensure_ascii=False, indent=1) + ' as const')
